# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/onex.
#

version: v2.0
  
on:
  push: [ master ]

steps:
- checkout: self
- run: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/hack/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh
    helm plugin install https://github.com/chartmuseum/helm-push.git
    ACCESS_TOKEN=${{ settings.HelmRepoToken.access_token }} make upload
  name: "Build and Push helm chart packages to helm repo"
 
notices:
- type: wework-message
