# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/onex.
#

apiVersion: apps.onex.io/v1beta1
kind: MinerSet
metadata:
  name: test
  namespace: user-admin
spec:
  deletePolicy: Random
  displayName: testminerset
  replicas: 2
  template:
    spec:
      chainName: genesis
      minerType: M1.MEDIUM2
