# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/onex.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - args:
        - --secure-port={{ .Values.args.securePort }}
        - --etcd-cafile={{ .Values.args.etcdCAFile }}
        - --etcd-servers={{ .Values.args.etcdServers }}
        - --etcd-certfile={{ .Values.args.etcdCertFile }}
        - --etcd-keyfile={{ .Values.args.etcdKeyFile }}
        - --disable-admission-plugins={{ .Values.args.disableAdmissionPlugins }}
        - --enable-admission-plugins={{ .Values.args.enableAdmissionPlugins }}
        - --max-requests-inflight={{ .Values.args.maxRequestsInflight }}
        - --max-mutating-requests-inflight={{ .Values.args.maxMutatingRequestsInflight }}
        - --client-ca-file={{ .Values.args.clientCAFile }}
        - --tls-cert-file={{ .Values.args.tlsCertFile }}
        - --tls-private-key-file={{ .Values.args.tlsPrivateKeyFile }}
        - --v=7
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 500m
            memory: 1G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/etcdcert
          name: {{ .Release.Name }}-etcd-certs
          readOnly: true
        - mountPath: /opt/onex/cert
          name: onex-tls
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {{ .Values.securityContext }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Release.Name }}-etcd-certs
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-etcd-certs
      - name: onex-tls
        configMap:
          defaultMode: 420
          name: onex-tls
