# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/onex.
#


apiVersion: v1
kind: Namespace
metadata:
    name: chain-master
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: genesis
  name: genesis
  namespace: chain-master
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: genesis
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: genesis # 资源标签
  name: genesis # 资源名称
  namespace: chain-master
spec:
  replicas: 1 # 副本数
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: genesis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: genesis
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - genesis
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - --disable-ssl
        - --mining-difficulty=2
        - --ip=0.0.0.0
        - --port=8080
        - --bootstrap-ip=0.0.0.0
        - --bootstrap-port=8080
        - --bootstrap-account=0x9049b2dcdb126e3003eff55f23bc3d7f570ce0e3
        - --miner=0x9049b2dcdb126e3003eff55f23bc3d7f570ce0e3
        - --datadir=/opt/tbb/data
        image: ccr.ccs.tencentyun.com/superproj/tbb:v0.0.2
        name: genesis
        ports:
        - containerPort: 8080
          name: http-insecure
          protocol: TCP
        resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/tbb/data
          name: genesis-database
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      volumes:
      - hostPath:
          path: /data/genesis-database
          type: DirectoryOrCreate
        name: genesis-database
