# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/onex.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian12-deployment
  labels:
    app: debian12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian12
  template:
    metadata:
      labels:
        app: debian12
    spec:
      containers:
      - name: debian12
        image: debian:12
        command: ["sleep", "infinity"]
        args: ["while true; do sleep 30; done;"]
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
