# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/onex.
#

version: "0.1"
database:
  # consult[https://gorm.io/docs/connecting_to_the_database.html]"
  dsn: "onex:onex(#)666@tcp(127.0.0.1:3306)/onex?charset=utf8mb4&parseTime=true&loc=Local"
  # input mysql or postgres or sqlite or sqlserver. consult[https://gorm.io/docs/connecting_to_the_database.html]
  db: "mysql"
  # enter the required data table or leave it blank.You can input : orders,users,goods
  tables: "miner"
  # specify a directory for output
  outPath:  "../dao/query"
  # query code file name, default: gen.go
  outFile:  ""
  # generate unit test for query code
  withUnitTest: true
  # generated model code's package name
  modelPkgName: ""
  # generate with pointer when field is nullable
  fieldNullable: false
  # generate field with gorm index tag
  fieldWithIndexTag: true
  # generate field with gorm column type tag
  fieldWithTypeTag: true
