# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/onex.
#

# onex-toyblc 服务配置文件

address: ${ONEX_TOYBLC_ADDRESS}
miner: ${ONEX_TOYBLC_MINER}
p2p-addr: ${ONEX_TOYBLC_P2P_ADDR}
peers: ${ONEX_TOYBLC_PEERS}
http:
  addr: ${ONEX_TOYBLC_HTTP_ADDR}
log: # 使用默认值即可，不需要在 manifests/env.local 中配置
    level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
    format: console # 支持的日志输出格式，目前支持 console 和 json 两种。console 其实就是 text 格式。
    enable-color: true # 是否开启颜色输出，true: 是，false: 否
    disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
    disable-stacktrace: false # 是否再 panic 及以上级别禁止打印堆栈信息
    output-paths: [stdout] # 多个输出，逗号分开。stdout：标准输出，


