# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/onex.
#


apiVersion: onexcontrollermanager.config.onex.io/v1beta1
kind: OneXControllerManagerConfiguration
generic:
  metricsBindAddress: 0.0.0.0:${ONEX_CONTROLLER_MANAGER_METRICS_PORT}
  healthzBindAddress: 0.0.0.0:${ONEX_CONTROLLER_MANAGER_HEALTHZ_PORT}
  parallelism: 32
  mysql: 
    host: ${ONEX_MYSQL_ADDR}
    database: ${ONEX_MYSQL_DATABASE}
    username: ${ONEX_MYSQL_USERNAME}
    password: ${ONEX_MYSQL_PASSWORD}
  leaderElection: 
    leaderElect: false
