# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/onex.
#

# onex-gateway 服务配置文件
kubeconfig: ${ONEX_ADMIN_KUBECONFIG}
http:
  addr: ${ONEX_GATEWAY_HTTP_ADDR} # HTTP 服务监听地址
grpc:
  addr: ${ONEX_GATEWAY_GRPC_ADDR} # gRPC 服务监听地址
tls:
  use-tls: ${ONEX_GATEWAY_TLS_USE_TLS} # 是否启用 TLS
  cert: ${ONEX_GATEWAY_TLS_CERT} # TLS 证书路径
  key: ${ONEX_GATEWAY_TLS_KEY} # TLS 私钥路径
mysql:
  host: ${ONEX_MYSQL_ADDR} # 数据库主机地址
  database: ${ONEX_MYSQL_DATABASE} # 数据库名称
  username: ${ONEX_MYSQL_USERNAME} # 数据库用户名
  password: ${ONEX_MYSQL_PASSWORD} # 数据库密码
  log-level: ${ONEX_MYSQL_LOG_LEVEL} # 数据库日志级别，1 为最低，4 为最高
etcd:
  endpoints: ${ONEX_ETCD_ENDPOINTS} # etcd 服务地址
redis:
  addr: ${ONEX_REDIS_ADDR}
  database: ${ONEX_GATEWAY_REDIS_DATABASE}
  password: ${ONEX_REDIS_PASSWORD}
usercenter:
  server: ${ONEX_GATEWAY_USERCENTER_SERVER} # onex-usercenter 服务地址
jaeger:
  env: ${ONEX_JAEGER_ENV} # Jaeger 环境
  server: ${ONEX_JAEGER_ENDPOINT} # Jaeger 服务地址
  service-name: onex-gateway # Jaeger 服务名称
log: # 使用默认值即可，不需要在 manifests/env.local 中配置
    level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
    format: console # 支持的日志输出格式，目前支持 console 和 json 两种。console 其实就是 text 格式。
    enable-color: true # 是否开启颜色输出，true: 是，false: 否
    disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
    disable-stacktrace: false # 是否再 panic 及以上级别禁止打印堆栈信息
    output-paths: [${ONEX_GATEWAY_LOG_OUTPUT}] # 多个输出，逗号分开。stdout：标准输出，
